# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.list_enrollment_token_reply import ListEnrollmentTokenReply


class TestListEnrollmentTokenReply(unittest.TestCase):
    """ ListEnrollmentTokenReply unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListEnrollmentTokenReply(self):
        """
        Test ListEnrollmentTokenReply
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.list_enrollment_token_reply.ListEnrollmentTokenReply()
        pass


if __name__ == '__main__':
    unittest.main()
