# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.clusters_kibana_api import ClustersKibanaApi


class TestClustersKibanaApi(unittest.TestCase):
    """ ClustersKibanaApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.clusters_kibana_api.ClustersKibanaApi()

    def tearDown(self):
        pass

    def test_cancel_kibana_cluster_pending_plan(self):
        """
        Test case for cancel_kibana_cluster_pending_plan

        Cancel pending plan
        """
        pass

    def test_create_kibana_cluster(self):
        """
        Test case for create_kibana_cluster

        Create cluster
        """
        pass

    def test_delete_kibana_cluster(self):
        """
        Test case for delete_kibana_cluster

        Delete cluster
        """
        pass

    def test_get_kibana_cluster(self):
        """
        Test case for get_kibana_cluster

        Get cluster
        """
        pass

    def test_get_kibana_cluster_metadata_raw(self):
        """
        Test case for get_kibana_cluster_metadata_raw

        Get cluster metadata
        """
        pass

    def test_get_kibana_cluster_metadata_settings(self):
        """
        Test case for get_kibana_cluster_metadata_settings

        Get cluster metadata settings
        """
        pass

    def test_get_kibana_cluster_pending_plan(self):
        """
        Test case for get_kibana_cluster_pending_plan

        Get pending plan
        """
        pass

    def test_get_kibana_cluster_plan(self):
        """
        Test case for get_kibana_cluster_plan

        Get plan
        """
        pass

    def test_get_kibana_cluster_plan_activity(self):
        """
        Test case for get_kibana_cluster_plan_activity

        Get plan activity
        """
        pass

    def test_get_kibana_clusters(self):
        """
        Test case for get_kibana_clusters

        Get clusters
        """
        pass

    def test_move_kibana_cluster_instances(self):
        """
        Test case for move_kibana_cluster_instances

        Move instances
        """
        pass

    def test_move_kibana_cluster_instances_advanced(self):
        """
        Test case for move_kibana_cluster_instances_advanced

        Move instances (advanced)
        """
        pass

    def test_restart_kibana_cluster(self):
        """
        Test case for restart_kibana_cluster

        Restart cluster
        """
        pass

    def test_set_kibana_cluster_metadata_raw(self):
        """
        Test case for set_kibana_cluster_metadata_raw

        Set cluster metadata
        """
        pass

    def test_set_kibana_cluster_name(self):
        """
        Test case for set_kibana_cluster_name

        Set cluster name
        """
        pass

    def test_shutdown_kibana_cluster(self):
        """
        Test case for shutdown_kibana_cluster

        Shut down cluster
        """
        pass

    def test_start_kibana_cluster_instances(self):
        """
        Test case for start_kibana_cluster_instances

        Start instances
        """
        pass

    def test_start_kibana_cluster_maintenance_mode(self):
        """
        Test case for start_kibana_cluster_maintenance_mode

        Start maintenance mode
        """
        pass

    def test_stop_kibana_cluster_instances(self):
        """
        Test case for stop_kibana_cluster_instances

        Stop instances
        """
        pass

    def test_stop_kibana_cluster_maintenance_mode(self):
        """
        Test case for stop_kibana_cluster_maintenance_mode

        Stop maintenance mode
        """
        pass

    def test_update_kibana_cluster_metadata_settings(self):
        """
        Test case for update_kibana_cluster_metadata_settings

        Update cluster metadata settings
        """
        pass

    def test_update_kibana_cluster_plan(self):
        """
        Test case for update_kibana_cluster_plan

        Update plan
        """
        pass


if __name__ == '__main__':
    unittest.main()
