# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.platform_configuration_snapshots_api import PlatformConfigurationSnapshotsApi


class TestPlatformConfigurationSnapshotsApi(unittest.TestCase):
    """ PlatformConfigurationSnapshotsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.platform_configuration_snapshots_api.PlatformConfigurationSnapshotsApi()

    def tearDown(self):
        pass

    def test_delete_snapshot_repository(self):
        """
        Test case for delete_snapshot_repository

        Delete snapshot repository
        """
        pass

    def test_get_snapshot_repositories(self):
        """
        Test case for get_snapshot_repositories

        Get snapshot repositories
        """
        pass

    def test_get_snapshot_repository(self):
        """
        Test case for get_snapshot_repository

        Get snapshot repository
        """
        pass

    def test_set_snapshot_repository(self):
        """
        Test case for set_snapshot_repository

        Set snapshot repository
        """
        pass


if __name__ == '__main__':
    unittest.main()
