# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.elasticsearch_node_type import ElasticsearchNodeType


class TestElasticsearchNodeType(unittest.TestCase):
    """ ElasticsearchNodeType unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testElasticsearchNodeType(self):
        """
        Test ElasticsearchNodeType
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.elasticsearch_node_type.ElasticsearchNodeType()
        pass


if __name__ == '__main__':
    unittest.main()
