# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.stack_version_archive_processing_error import StackVersionArchiveProcessingError


class TestStackVersionArchiveProcessingError(unittest.TestCase):
    """ StackVersionArchiveProcessingError unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStackVersionArchiveProcessingError(self):
        """
        Test StackVersionArchiveProcessingError
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.stack_version_archive_processing_error.StackVersionArchiveProcessingError()
        pass


if __name__ == '__main__':
    unittest.main()
