# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.platform_configuration_security_api import PlatformConfigurationSecurityApi


class TestPlatformConfigurationSecurityApi(unittest.TestCase):
    """ PlatformConfigurationSecurityApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.platform_configuration_security_api.PlatformConfigurationSecurityApi()

    def tearDown(self):
        pass

    def test_create_enrollment_token(self):
        """
        Test case for create_enrollment_token

        Create enrollment token
        """
        pass

    def test_delete_enrollment_token(self):
        """
        Test case for delete_enrollment_token

        Delete enrollment token
        """
        pass

    def test_get_enrollment_tokens(self):
        """
        Test case for get_enrollment_tokens

        Get enrollment tokens
        """
        pass

    def test_get_tls_certificate(self):
        """
        Test case for get_tls_certificate

        Get TLS certificate
        """
        pass

    def test_set_tls_certificate(self):
        """
        Test case for set_tls_certificate

        Set TLS certificate
        """
        pass


if __name__ == '__main__':
    unittest.main()
