# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.stack_api import StackApi


class TestStackApi(unittest.TestCase):
    """ StackApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.stack_api.StackApi()

    def tearDown(self):
        pass

    def test_delete_version_stack(self):
        """
        Test case for delete_version_stack

        Mark an Elastic Stack version for deletion
        """
        pass

    def test_get_version_stack(self):
        """
        Test case for get_version_stack

        Get an Elastic Stack version
        """
        pass

    def test_get_version_stacks(self):
        """
        Test case for get_version_stacks

        Get all available Elastic Stack versions
        """
        pass

    def test_update_stack_packs(self):
        """
        Test case for update_stack_packs

        Submit Elastic Stack packs
        """
        pass

    def test_update_version_stack(self):
        """
        Test case for update_version_stack

        Update an Elastic Stack version
        """
        pass


if __name__ == '__main__':
    unittest.main()
