# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AllocatorCapacityMemory(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'int',
        'used': 'int'
    }

    attribute_map = {
        'total': 'total',
        'used': 'used'
    }

    def __init__(self, total=None, used=None):
        """
        AllocatorCapacityMemory - a model defined in Swagger
        """

        self._total = None
        self._used = None

        if total is not None:
          self.total = total
        if used is not None:
          self.used = used

    @property
    def total(self):
        """
        Gets the total of this AllocatorCapacityMemory.
        Total memory in MB capacity installed on this allocator

        :return: The total of this AllocatorCapacityMemory.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this AllocatorCapacityMemory.
        Total memory in MB capacity installed on this allocator

        :param total: The total of this AllocatorCapacityMemory.
        :type: int
        """

        self._total = total

    @property
    def used(self):
        """
        Gets the used of this AllocatorCapacityMemory.
        Used memory in MB used by instances assigned to this allocator

        :return: The used of this AllocatorCapacityMemory.
        :rtype: int
        """
        return self._used

    @used.setter
    def used(self, used):
        """
        Sets the used of this AllocatorCapacityMemory.
        Used memory in MB used by instances assigned to this allocator

        :param used: The used of this AllocatorCapacityMemory.
        :type: int
        """

        self._used = used

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AllocatorCapacityMemory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
