# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AllocatorZoneInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'zone_id': 'str',
        'allocators': 'list[AllocatorInfo]'
    }

    attribute_map = {
        'zone_id': 'zone_id',
        'allocators': 'allocators'
    }

    def __init__(self, zone_id=None, allocators=None):
        """
        AllocatorZoneInfo - a model defined in Swagger
        """

        self._zone_id = None
        self._allocators = None

        if zone_id is not None:
          self.zone_id = zone_id
        if allocators is not None:
          self.allocators = allocators

    @property
    def zone_id(self):
        """
        Gets the zone_id of this AllocatorZoneInfo.
        Identifier of the zone

        :return: The zone_id of this AllocatorZoneInfo.
        :rtype: str
        """
        return self._zone_id

    @zone_id.setter
    def zone_id(self, zone_id):
        """
        Sets the zone_id of this AllocatorZoneInfo.
        Identifier of the zone

        :param zone_id: The zone_id of this AllocatorZoneInfo.
        :type: str
        """

        self._zone_id = zone_id

    @property
    def allocators(self):
        """
        Gets the allocators of this AllocatorZoneInfo.

        :return: The allocators of this AllocatorZoneInfo.
        :rtype: list[AllocatorInfo]
        """
        return self._allocators

    @allocators.setter
    def allocators(self, allocators):
        """
        Sets the allocators of this AllocatorZoneInfo.

        :param allocators: The allocators of this AllocatorZoneInfo.
        :type: list[AllocatorInfo]
        """

        self._allocators = allocators

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AllocatorZoneInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
