# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BasicFailedReplyElement(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'message': 'str',
        'fields': 'list[str]'
    }

    attribute_map = {
        'code': 'code',
        'message': 'message',
        'fields': 'fields'
    }

    def __init__(self, code=None, message=None, fields=None):
        """
        BasicFailedReplyElement - a model defined in Swagger
        """

        self._code = None
        self._message = None
        self._fields = None

        self.code = code
        self.message = message
        if fields is not None:
          self.fields = fields

    @property
    def code(self):
        """
        Gets the code of this BasicFailedReplyElement.
        A structured code representing the error type that occurred

        :return: The code of this BasicFailedReplyElement.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this BasicFailedReplyElement.
        A structured code representing the error type that occurred

        :param code: The code of this BasicFailedReplyElement.
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def message(self):
        """
        Gets the message of this BasicFailedReplyElement.
        A human readable message describing the error that occurred

        :return: The message of this BasicFailedReplyElement.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this BasicFailedReplyElement.
        A human readable message describing the error that occurred

        :param message: The message of this BasicFailedReplyElement.
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")

        self._message = message

    @property
    def fields(self):
        """
        Gets the fields of this BasicFailedReplyElement.
        If the error can be tied to a specific field or fields in the user request, this lists those fields

        :return: The fields of this BasicFailedReplyElement.
        :rtype: list[str]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """
        Sets the fields of this BasicFailedReplyElement.
        If the error can be tied to a specific field or fields in the user request, this lists those fields

        :param fields: The fields of this BasicFailedReplyElement.
        :type: list[str]
        """

        self._fields = fields

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BasicFailedReplyElement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
