# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClusterInstanceDiskInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'disk_space_available': 'int',
        'disk_space_used': 'int'
    }

    attribute_map = {
        'disk_space_available': 'disk_space_available',
        'disk_space_used': 'disk_space_used'
    }

    def __init__(self, disk_space_available=None, disk_space_used=None):
        """
        ClusterInstanceDiskInfo - a model defined in Swagger
        """

        self._disk_space_available = None
        self._disk_space_used = None

        if disk_space_available is not None:
          self.disk_space_available = disk_space_available
        self.disk_space_used = disk_space_used

    @property
    def disk_space_available(self):
        """
        Gets the disk_space_available of this ClusterInstanceDiskInfo.
        If known, the amount of disk space available to the container in MB

        :return: The disk_space_available of this ClusterInstanceDiskInfo.
        :rtype: int
        """
        return self._disk_space_available

    @disk_space_available.setter
    def disk_space_available(self, disk_space_available):
        """
        Sets the disk_space_available of this ClusterInstanceDiskInfo.
        If known, the amount of disk space available to the container in MB

        :param disk_space_available: The disk_space_available of this ClusterInstanceDiskInfo.
        :type: int
        """

        self._disk_space_available = disk_space_available

    @property
    def disk_space_used(self):
        """
        Gets the disk_space_used of this ClusterInstanceDiskInfo.
        The amount of disk space being used by the service in MB

        :return: The disk_space_used of this ClusterInstanceDiskInfo.
        :rtype: int
        """
        return self._disk_space_used

    @disk_space_used.setter
    def disk_space_used(self, disk_space_used):
        """
        Sets the disk_space_used of this ClusterInstanceDiskInfo.
        The amount of disk space being used by the service in MB

        :param disk_space_used: The disk_space_used of this ClusterInstanceDiskInfo.
        :type: int
        """
        if disk_space_used is None:
            raise ValueError("Invalid value for `disk_space_used`, must not be `None`")

        self._disk_space_used = disk_space_used

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClusterInstanceDiskInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
