# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClusterCommandResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'calculated_elasticsearch_plan': 'ElasticsearchPlanControlConfiguration',
        'calculated_kibana_plan': 'KibanaPlanControlConfiguration'
    }

    attribute_map = {
        'calculated_elasticsearch_plan': 'calculated_elasticsearch_plan',
        'calculated_kibana_plan': 'calculated_kibana_plan'
    }

    def __init__(self, calculated_elasticsearch_plan=None, calculated_kibana_plan=None):
        """
        ClusterCommandResponse - a model defined in Swagger
        """

        self._calculated_elasticsearch_plan = None
        self._calculated_kibana_plan = None

        if calculated_elasticsearch_plan is not None:
          self.calculated_elasticsearch_plan = calculated_elasticsearch_plan
        if calculated_kibana_plan is not None:
          self.calculated_kibana_plan = calculated_kibana_plan

    @property
    def calculated_elasticsearch_plan(self):
        """
        Gets the calculated_elasticsearch_plan of this ClusterCommandResponse.
        If validating the command only, then the calculated Elasticsearch plan that would be applied.

        :return: The calculated_elasticsearch_plan of this ClusterCommandResponse.
        :rtype: ElasticsearchPlanControlConfiguration
        """
        return self._calculated_elasticsearch_plan

    @calculated_elasticsearch_plan.setter
    def calculated_elasticsearch_plan(self, calculated_elasticsearch_plan):
        """
        Sets the calculated_elasticsearch_plan of this ClusterCommandResponse.
        If validating the command only, then the calculated Elasticsearch plan that would be applied.

        :param calculated_elasticsearch_plan: The calculated_elasticsearch_plan of this ClusterCommandResponse.
        :type: ElasticsearchPlanControlConfiguration
        """

        self._calculated_elasticsearch_plan = calculated_elasticsearch_plan

    @property
    def calculated_kibana_plan(self):
        """
        Gets the calculated_kibana_plan of this ClusterCommandResponse.
        If validating the command only, then the calculated Kibana plan that would be applied.

        :return: The calculated_kibana_plan of this ClusterCommandResponse.
        :rtype: KibanaPlanControlConfiguration
        """
        return self._calculated_kibana_plan

    @calculated_kibana_plan.setter
    def calculated_kibana_plan(self, calculated_kibana_plan):
        """
        Sets the calculated_kibana_plan of this ClusterCommandResponse.
        If validating the command only, then the calculated Kibana plan that would be applied.

        :param calculated_kibana_plan: The calculated_kibana_plan of this ClusterCommandResponse.
        :type: KibanaPlanControlConfiguration
        """

        self._calculated_kibana_plan = calculated_kibana_plan

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClusterCommandResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
