# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ElasticsearchClusterBlockingIssues(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'healthy': 'bool',
        'cluster_level': 'list[ElasticsearchClusterBlockingIssueElement]',
        'index_level': 'list[ElasticsearchClusterBlockingIssueElement]'
    }

    attribute_map = {
        'healthy': 'healthy',
        'cluster_level': 'cluster_level',
        'index_level': 'index_level'
    }

    def __init__(self, healthy=None, cluster_level=None, index_level=None):
        """
        ElasticsearchClusterBlockingIssues - a model defined in Swagger
        """

        self._healthy = None
        self._cluster_level = None
        self._index_level = None

        if healthy is not None:
          self.healthy = healthy
        if cluster_level is not None:
          self.cluster_level = cluster_level
        if index_level is not None:
          self.index_level = index_level

    @property
    def healthy(self):
        """
        Gets the healthy of this ElasticsearchClusterBlockingIssues.
        Whether the cluster has issues (false) or not (true)

        :return: The healthy of this ElasticsearchClusterBlockingIssues.
        :rtype: bool
        """
        return self._healthy

    @healthy.setter
    def healthy(self, healthy):
        """
        Sets the healthy of this ElasticsearchClusterBlockingIssues.
        Whether the cluster has issues (false) or not (true)

        :param healthy: The healthy of this ElasticsearchClusterBlockingIssues.
        :type: bool
        """

        self._healthy = healthy

    @property
    def cluster_level(self):
        """
        Gets the cluster_level of this ElasticsearchClusterBlockingIssues.
        A list of issues that affect availability of entire cluster

        :return: The cluster_level of this ElasticsearchClusterBlockingIssues.
        :rtype: list[ElasticsearchClusterBlockingIssueElement]
        """
        return self._cluster_level

    @cluster_level.setter
    def cluster_level(self, cluster_level):
        """
        Sets the cluster_level of this ElasticsearchClusterBlockingIssues.
        A list of issues that affect availability of entire cluster

        :param cluster_level: The cluster_level of this ElasticsearchClusterBlockingIssues.
        :type: list[ElasticsearchClusterBlockingIssueElement]
        """

        self._cluster_level = cluster_level

    @property
    def index_level(self):
        """
        Gets the index_level of this ElasticsearchClusterBlockingIssues.
        A list of issues that affect availability of the cluster's indices

        :return: The index_level of this ElasticsearchClusterBlockingIssues.
        :rtype: list[ElasticsearchClusterBlockingIssueElement]
        """
        return self._index_level

    @index_level.setter
    def index_level(self, index_level):
        """
        Sets the index_level of this ElasticsearchClusterBlockingIssues.
        A list of issues that affect availability of the cluster's indices

        :param index_level: The index_level of this ElasticsearchClusterBlockingIssues.
        :type: list[ElasticsearchClusterBlockingIssueElement]
        """

        self._index_level = index_level

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ElasticsearchClusterBlockingIssues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
