# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ElasticsearchClusterBlockingIssueElement(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'instances': 'list[str]'
    }

    attribute_map = {
        'description': 'description',
        'instances': 'instances'
    }

    def __init__(self, description=None, instances=None):
        """
        ElasticsearchClusterBlockingIssueElement - a model defined in Swagger
        """

        self._description = None
        self._instances = None

        if description is not None:
          self.description = description
        if instances is not None:
          self.instances = instances

    @property
    def description(self):
        """
        Gets the description of this ElasticsearchClusterBlockingIssueElement.
        Description of the issue

        :return: The description of this ElasticsearchClusterBlockingIssueElement.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this ElasticsearchClusterBlockingIssueElement.
        Description of the issue

        :param description: The description of this ElasticsearchClusterBlockingIssueElement.
        :type: str
        """

        self._description = description

    @property
    def instances(self):
        """
        Gets the instances of this ElasticsearchClusterBlockingIssueElement.
        A list of instances that are affected by the issue

        :return: The instances of this ElasticsearchClusterBlockingIssueElement.
        :rtype: list[str]
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """
        Sets the instances of this ElasticsearchClusterBlockingIssueElement.
        A list of instances that are affected by the issue

        :param instances: The instances of this ElasticsearchClusterBlockingIssueElement.
        :type: list[str]
        """

        self._instances = instances

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ElasticsearchClusterBlockingIssueElement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
