# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ElasticsearchShardsInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'healthy': 'bool',
        'available_shards': 'list[ElasticsearchShardElement]',
        'unavailable_shards': 'list[ElasticsearchShardElement]',
        'unavailable_replicas': 'list[ElasticsearchReplicaElement]'
    }

    attribute_map = {
        'healthy': 'healthy',
        'available_shards': 'available_shards',
        'unavailable_shards': 'unavailable_shards',
        'unavailable_replicas': 'unavailable_replicas'
    }

    def __init__(self, healthy=None, available_shards=None, unavailable_shards=None, unavailable_replicas=None):
        """
        ElasticsearchShardsInfo - a model defined in Swagger
        """

        self._healthy = None
        self._available_shards = None
        self._unavailable_shards = None
        self._unavailable_replicas = None

        self.healthy = healthy
        self.available_shards = available_shards
        self.unavailable_shards = unavailable_shards
        self.unavailable_replicas = unavailable_replicas

    @property
    def healthy(self):
        """
        Gets the healthy of this ElasticsearchShardsInfo.
        Whether the shard situation is healthy (any unavailable shards is unhealthy)

        :return: The healthy of this ElasticsearchShardsInfo.
        :rtype: bool
        """
        return self._healthy

    @healthy.setter
    def healthy(self, healthy):
        """
        Sets the healthy of this ElasticsearchShardsInfo.
        Whether the shard situation is healthy (any unavailable shards is unhealthy)

        :param healthy: The healthy of this ElasticsearchShardsInfo.
        :type: bool
        """
        if healthy is None:
            raise ValueError("Invalid value for `healthy`, must not be `None`")

        self._healthy = healthy

    @property
    def available_shards(self):
        """
        Gets the available_shards of this ElasticsearchShardsInfo.

        :return: The available_shards of this ElasticsearchShardsInfo.
        :rtype: list[ElasticsearchShardElement]
        """
        return self._available_shards

    @available_shards.setter
    def available_shards(self, available_shards):
        """
        Sets the available_shards of this ElasticsearchShardsInfo.

        :param available_shards: The available_shards of this ElasticsearchShardsInfo.
        :type: list[ElasticsearchShardElement]
        """
        if available_shards is None:
            raise ValueError("Invalid value for `available_shards`, must not be `None`")

        self._available_shards = available_shards

    @property
    def unavailable_shards(self):
        """
        Gets the unavailable_shards of this ElasticsearchShardsInfo.

        :return: The unavailable_shards of this ElasticsearchShardsInfo.
        :rtype: list[ElasticsearchShardElement]
        """
        return self._unavailable_shards

    @unavailable_shards.setter
    def unavailable_shards(self, unavailable_shards):
        """
        Sets the unavailable_shards of this ElasticsearchShardsInfo.

        :param unavailable_shards: The unavailable_shards of this ElasticsearchShardsInfo.
        :type: list[ElasticsearchShardElement]
        """
        if unavailable_shards is None:
            raise ValueError("Invalid value for `unavailable_shards`, must not be `None`")

        self._unavailable_shards = unavailable_shards

    @property
    def unavailable_replicas(self):
        """
        Gets the unavailable_replicas of this ElasticsearchShardsInfo.

        :return: The unavailable_replicas of this ElasticsearchShardsInfo.
        :rtype: list[ElasticsearchReplicaElement]
        """
        return self._unavailable_replicas

    @unavailable_replicas.setter
    def unavailable_replicas(self, unavailable_replicas):
        """
        Sets the unavailable_replicas of this ElasticsearchShardsInfo.

        :param unavailable_replicas: The unavailable_replicas of this ElasticsearchShardsInfo.
        :type: list[ElasticsearchReplicaElement]
        """
        if unavailable_replicas is None:
            raise ValueError("Invalid value for `unavailable_replicas`, must not be `None`")

        self._unavailable_replicas = unavailable_replicas

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ElasticsearchShardsInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
