# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ElasticsearchReplicaElement(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instance_name': 'str',
        'replica_count': 'int'
    }

    attribute_map = {
        'instance_name': 'instance_name',
        'replica_count': 'replica_count'
    }

    def __init__(self, instance_name=None, replica_count=None):
        """
        ElasticsearchReplicaElement - a model defined in Swagger
        """

        self._instance_name = None
        self._replica_count = None

        self.instance_name = instance_name
        self.replica_count = replica_count

    @property
    def instance_name(self):
        """
        Gets the instance_name of this ElasticsearchReplicaElement.
        The Elastic Cloud name/id of the instance (container)

        :return: The instance_name of this ElasticsearchReplicaElement.
        :rtype: str
        """
        return self._instance_name

    @instance_name.setter
    def instance_name(self, instance_name):
        """
        Sets the instance_name of this ElasticsearchReplicaElement.
        The Elastic Cloud name/id of the instance (container)

        :param instance_name: The instance_name of this ElasticsearchReplicaElement.
        :type: str
        """
        if instance_name is None:
            raise ValueError("Invalid value for `instance_name`, must not be `None`")

        self._instance_name = instance_name

    @property
    def replica_count(self):
        """
        Gets the replica_count of this ElasticsearchReplicaElement.
        The number of unavailable replicas on this instance

        :return: The replica_count of this ElasticsearchReplicaElement.
        :rtype: int
        """
        return self._replica_count

    @replica_count.setter
    def replica_count(self, replica_count):
        """
        Sets the replica_count of this ElasticsearchReplicaElement.
        The number of unavailable replicas on this instance

        :param replica_count: The replica_count of this ElasticsearchReplicaElement.
        :type: int
        """
        if replica_count is None:
            raise ValueError("Invalid value for `replica_count`, must not be `None`")

        self._replica_count = replica_count

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ElasticsearchReplicaElement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
