# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ElasticsearchClusterInstanceSettingsOverrides(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instance_capacity': 'int'
    }

    attribute_map = {
        'instance_capacity': 'instance_capacity'
    }

    def __init__(self, instance_capacity=None):
        """
        ElasticsearchClusterInstanceSettingsOverrides - a model defined in Swagger
        """

        self._instance_capacity = None

        if instance_capacity is not None:
          self.instance_capacity = instance_capacity

    @property
    def instance_capacity(self):
        """
        Gets the instance_capacity of this ElasticsearchClusterInstanceSettingsOverrides.
        Sets the memory capacity for the instance's container. Requires a restart to take effect.

        :return: The instance_capacity of this ElasticsearchClusterInstanceSettingsOverrides.
        :rtype: int
        """
        return self._instance_capacity

    @instance_capacity.setter
    def instance_capacity(self, instance_capacity):
        """
        Sets the instance_capacity of this ElasticsearchClusterInstanceSettingsOverrides.
        Sets the memory capacity for the instance's container. Requires a restart to take effect.

        :param instance_capacity: The instance_capacity of this ElasticsearchClusterInstanceSettingsOverrides.
        :type: int
        """

        self._instance_capacity = instance_capacity

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ElasticsearchClusterInstanceSettingsOverrides):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
