# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ElasticsearchMasterInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'healthy': 'bool',
        'masters': 'list[ElasticsearchMasterElement]',
        'instances_with_no_master': 'list[str]'
    }

    attribute_map = {
        'healthy': 'healthy',
        'masters': 'masters',
        'instances_with_no_master': 'instances_with_no_master'
    }

    def __init__(self, healthy=None, masters=None, instances_with_no_master=None):
        """
        ElasticsearchMasterInfo - a model defined in Swagger
        """

        self._healthy = None
        self._masters = None
        self._instances_with_no_master = None

        self.healthy = healthy
        self.masters = masters
        self.instances_with_no_master = instances_with_no_master

    @property
    def healthy(self):
        """
        Gets the healthy of this ElasticsearchMasterInfo.
        Whether the master situation in the cluster is healthy (ie is the number of masters != 1), or do any instances have no master

        :return: The healthy of this ElasticsearchMasterInfo.
        :rtype: bool
        """
        return self._healthy

    @healthy.setter
    def healthy(self, healthy):
        """
        Sets the healthy of this ElasticsearchMasterInfo.
        Whether the master situation in the cluster is healthy (ie is the number of masters != 1), or do any instances have no master

        :param healthy: The healthy of this ElasticsearchMasterInfo.
        :type: bool
        """
        if healthy is None:
            raise ValueError("Invalid value for `healthy`, must not be `None`")

        self._healthy = healthy

    @property
    def masters(self):
        """
        Gets the masters of this ElasticsearchMasterInfo.

        :return: The masters of this ElasticsearchMasterInfo.
        :rtype: list[ElasticsearchMasterElement]
        """
        return self._masters

    @masters.setter
    def masters(self, masters):
        """
        Sets the masters of this ElasticsearchMasterInfo.

        :param masters: The masters of this ElasticsearchMasterInfo.
        :type: list[ElasticsearchMasterElement]
        """
        if masters is None:
            raise ValueError("Invalid value for `masters`, must not be `None`")

        self._masters = masters

    @property
    def instances_with_no_master(self):
        """
        Gets the instances_with_no_master of this ElasticsearchMasterInfo.
        A list of any instances with no master

        :return: The instances_with_no_master of this ElasticsearchMasterInfo.
        :rtype: list[str]
        """
        return self._instances_with_no_master

    @instances_with_no_master.setter
    def instances_with_no_master(self, instances_with_no_master):
        """
        Sets the instances_with_no_master of this ElasticsearchMasterInfo.
        A list of any instances with no master

        :param instances_with_no_master: The instances_with_no_master of this ElasticsearchMasterInfo.
        :type: list[str]
        """
        if instances_with_no_master is None:
            raise ValueError("Invalid value for `instances_with_no_master`, must not be `None`")

        self._instances_with_no_master = instances_with_no_master

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ElasticsearchMasterInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
