# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class KibanaClustersInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'return_count': 'int',
        'kibana_clusters': 'list[KibanaClusterInfo]'
    }

    attribute_map = {
        'return_count': 'return_count',
        'kibana_clusters': 'kibana_clusters'
    }

    def __init__(self, return_count=None, kibana_clusters=None):
        """
        KibanaClustersInfo - a model defined in Swagger
        """

        self._return_count = None
        self._kibana_clusters = None

        self.return_count = return_count
        self.kibana_clusters = kibana_clusters

    @property
    def return_count(self):
        """
        Gets the return_count of this KibanaClustersInfo.
        The number of clusters actually returned

        :return: The return_count of this KibanaClustersInfo.
        :rtype: int
        """
        return self._return_count

    @return_count.setter
    def return_count(self, return_count):
        """
        Sets the return_count of this KibanaClustersInfo.
        The number of clusters actually returned

        :param return_count: The return_count of this KibanaClustersInfo.
        :type: int
        """
        if return_count is None:
            raise ValueError("Invalid value for `return_count`, must not be `None`")

        self._return_count = return_count

    @property
    def kibana_clusters(self):
        """
        Gets the kibana_clusters of this KibanaClustersInfo.

        :return: The kibana_clusters of this KibanaClustersInfo.
        :rtype: list[KibanaClusterInfo]
        """
        return self._kibana_clusters

    @kibana_clusters.setter
    def kibana_clusters(self, kibana_clusters):
        """
        Sets the kibana_clusters of this KibanaClustersInfo.

        :param kibana_clusters: The kibana_clusters of this KibanaClustersInfo.
        :type: list[KibanaClusterInfo]
        """
        if kibana_clusters is None:
            raise ValueError("Invalid value for `kibana_clusters`, must not be `None`")

        self._kibana_clusters = kibana_clusters

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, KibanaClustersInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
