# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ListEnrollmentTokenReply(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tokens': 'list[ListEnrollmentTokenElement]'
    }

    attribute_map = {
        'tokens': 'tokens'
    }

    def __init__(self, tokens=None):
        """
        ListEnrollmentTokenReply - a model defined in Swagger
        """

        self._tokens = None

        if tokens is not None:
          self.tokens = tokens

    @property
    def tokens(self):
        """
        Gets the tokens of this ListEnrollmentTokenReply.
        The list of currently active enrollment tokens

        :return: The tokens of this ListEnrollmentTokenReply.
        :rtype: list[ListEnrollmentTokenElement]
        """
        return self._tokens

    @tokens.setter
    def tokens(self, tokens):
        """
        Sets the tokens of this ListEnrollmentTokenReply.
        The list of currently active enrollment tokens

        :param tokens: The tokens of this ListEnrollmentTokenReply.
        :type: list[ListEnrollmentTokenElement]
        """

        self._tokens = tokens

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ListEnrollmentTokenReply):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
