# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ManagedSnapshotSettings(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'repository_name': 'str',
        'interval': 'str'
    }

    attribute_map = {
        'repository_name': 'repository_name',
        'interval': 'interval'
    }

    def __init__(self, repository_name=None, interval=None):
        """
        ManagedSnapshotSettings - a model defined in Swagger
        """

        self._repository_name = None
        self._interval = None

        self.repository_name = repository_name
        if interval is not None:
          self.interval = interval

    @property
    def repository_name(self):
        """
        Gets the repository_name of this ManagedSnapshotSettings.
        ECE snapshot repository name, from the '/platform/configuration/snapshots/repositories' endpoint

        :return: The repository_name of this ManagedSnapshotSettings.
        :rtype: str
        """
        return self._repository_name

    @repository_name.setter
    def repository_name(self, repository_name):
        """
        Sets the repository_name of this ManagedSnapshotSettings.
        ECE snapshot repository name, from the '/platform/configuration/snapshots/repositories' endpoint

        :param repository_name: The repository_name of this ManagedSnapshotSettings.
        :type: str
        """
        if repository_name is None:
            raise ValueError("Invalid value for `repository_name`, must not be `None`")

        self._repository_name = repository_name

    @property
    def interval(self):
        """
        Gets the interval of this ManagedSnapshotSettings.
        Interval between snapshots, with the format 'length unit' (space is optional), where unit can be one of: d (day), h (hour), min (minute). Default is 30 minutes

        :return: The interval of this ManagedSnapshotSettings.
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """
        Sets the interval of this ManagedSnapshotSettings.
        Interval between snapshots, with the format 'length unit' (space is optional), where unit can be one of: d (day), h (hour), min (minute). Default is 30 minutes

        :param interval: The interval of this ManagedSnapshotSettings.
        :type: str
        """

        self._interval = interval

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ManagedSnapshotSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
