# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MoveClustersDetails(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'elasticsearch_clusters': 'list[MoveElasticsearchClusterDetails]',
        'kibana_clusters': 'list[MoveKibanaClusterDetails]'
    }

    attribute_map = {
        'elasticsearch_clusters': 'elasticsearch_clusters',
        'kibana_clusters': 'kibana_clusters'
    }

    def __init__(self, elasticsearch_clusters=None, kibana_clusters=None):
        """
        MoveClustersDetails - a model defined in Swagger
        """

        self._elasticsearch_clusters = None
        self._kibana_clusters = None

        if elasticsearch_clusters is not None:
          self.elasticsearch_clusters = elasticsearch_clusters
        if kibana_clusters is not None:
          self.kibana_clusters = kibana_clusters

    @property
    def elasticsearch_clusters(self):
        """
        Gets the elasticsearch_clusters of this MoveClustersDetails.
        Detailed information about the Elasticsearch clusters being moved.

        :return: The elasticsearch_clusters of this MoveClustersDetails.
        :rtype: list[MoveElasticsearchClusterDetails]
        """
        return self._elasticsearch_clusters

    @elasticsearch_clusters.setter
    def elasticsearch_clusters(self, elasticsearch_clusters):
        """
        Sets the elasticsearch_clusters of this MoveClustersDetails.
        Detailed information about the Elasticsearch clusters being moved.

        :param elasticsearch_clusters: The elasticsearch_clusters of this MoveClustersDetails.
        :type: list[MoveElasticsearchClusterDetails]
        """

        self._elasticsearch_clusters = elasticsearch_clusters

    @property
    def kibana_clusters(self):
        """
        Gets the kibana_clusters of this MoveClustersDetails.
        Detailed information about the Kibana clusters being moved.

        :return: The kibana_clusters of this MoveClustersDetails.
        :rtype: list[MoveKibanaClusterDetails]
        """
        return self._kibana_clusters

    @kibana_clusters.setter
    def kibana_clusters(self, kibana_clusters):
        """
        Sets the kibana_clusters of this MoveClustersDetails.
        Detailed information about the Kibana clusters being moved.

        :param kibana_clusters: The kibana_clusters of this MoveClustersDetails.
        :type: list[MoveKibanaClusterDetails]
        """

        self._kibana_clusters = kibana_clusters

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MoveClustersDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
