# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PlatformServiceInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'image': 'list[PlatformServiceImageInfo]'
    }

    attribute_map = {
        'type': 'type',
        'image': 'image'
    }

    def __init__(self, type=None, image=None):
        """
        PlatformServiceInfo - a model defined in Swagger
        """

        self._type = None
        self._image = None

        if type is not None:
          self.type = type
        if image is not None:
          self.image = image

    @property
    def type(self):
        """
        Gets the type of this PlatformServiceInfo.
        Name of service

        :return: The type of this PlatformServiceInfo.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this PlatformServiceInfo.
        Name of service

        :param type: The type of this PlatformServiceInfo.
        :type: str
        """

        self._type = type

    @property
    def image(self):
        """
        Gets the image of this PlatformServiceInfo.

        :return: The image of this PlatformServiceInfo.
        :rtype: list[PlatformServiceImageInfo]
        """
        return self._image

    @image.setter
    def image(self, image):
        """
        Sets the image of this PlatformServiceInfo.

        :param image: The image of this PlatformServiceInfo.
        :type: list[PlatformServiceImageInfo]
        """

        self._image = image

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PlatformServiceInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
