# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PlatformInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'services': 'list[PlatformServiceInfo]',
        'phone_home_enabled': 'bool',
        'eula_accepted': 'bool'
    }

    attribute_map = {
        'version': 'version',
        'services': 'services',
        'phone_home_enabled': 'phone_home_enabled',
        'eula_accepted': 'eula_accepted'
    }

    def __init__(self, version=None, services=None, phone_home_enabled=None, eula_accepted=None):
        """
        PlatformInfo - a model defined in Swagger
        """

        self._version = None
        self._services = None
        self._phone_home_enabled = None
        self._eula_accepted = None

        if version is not None:
          self.version = version
        if services is not None:
          self.services = services
        if phone_home_enabled is not None:
          self.phone_home_enabled = phone_home_enabled
        if eula_accepted is not None:
          self.eula_accepted = eula_accepted

    @property
    def version(self):
        """
        Gets the version of this PlatformInfo.
        Platform version

        :return: The version of this PlatformInfo.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this PlatformInfo.
        Platform version

        :param version: The version of this PlatformInfo.
        :type: str
        """

        self._version = version

    @property
    def services(self):
        """
        Gets the services of this PlatformInfo.

        :return: The services of this PlatformInfo.
        :rtype: list[PlatformServiceInfo]
        """
        return self._services

    @services.setter
    def services(self, services):
        """
        Sets the services of this PlatformInfo.

        :param services: The services of this PlatformInfo.
        :type: list[PlatformServiceInfo]
        """

        self._services = services

    @property
    def phone_home_enabled(self):
        """
        Gets the phone_home_enabled of this PlatformInfo.
        Is the phone-home service, which returns anonymized usage statistics to Elastic, enabled

        :return: The phone_home_enabled of this PlatformInfo.
        :rtype: bool
        """
        return self._phone_home_enabled

    @phone_home_enabled.setter
    def phone_home_enabled(self, phone_home_enabled):
        """
        Sets the phone_home_enabled of this PlatformInfo.
        Is the phone-home service, which returns anonymized usage statistics to Elastic, enabled

        :param phone_home_enabled: The phone_home_enabled of this PlatformInfo.
        :type: bool
        """

        self._phone_home_enabled = phone_home_enabled

    @property
    def eula_accepted(self):
        """
        Gets the eula_accepted of this PlatformInfo.
        Indicates if the End User License Agreement been accepted

        :return: The eula_accepted of this PlatformInfo.
        :rtype: bool
        """
        return self._eula_accepted

    @eula_accepted.setter
    def eula_accepted(self, eula_accepted):
        """
        Sets the eula_accepted of this PlatformInfo.
        Indicates if the End User License Agreement been accepted

        :param eula_accepted: The eula_accepted of this PlatformInfo.
        :type: bool
        """

        self._eula_accepted = eula_accepted

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PlatformInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
