# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class StackVersionConfig(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'template': 'StackVersionTemplateInfo',
        'elasticsearch': 'StackVersionElasticsearchConfig',
        'kibana': 'StackVersionKibanaConfig',
        'metadata': 'StackVersionMetadata',
        'deleted': 'bool'
    }

    attribute_map = {
        'version': 'version',
        'template': 'template',
        'elasticsearch': 'elasticsearch',
        'kibana': 'kibana',
        'metadata': 'metadata',
        'deleted': 'deleted'
    }

    def __init__(self, version=None, template=None, elasticsearch=None, kibana=None, metadata=None, deleted=None):
        """
        StackVersionConfig - a model defined in Swagger
        """

        self._version = None
        self._template = None
        self._elasticsearch = None
        self._kibana = None
        self._metadata = None
        self._deleted = None

        if version is not None:
          self.version = version
        if template is not None:
          self.template = template
        if elasticsearch is not None:
          self.elasticsearch = elasticsearch
        if kibana is not None:
          self.kibana = kibana
        if metadata is not None:
          self.metadata = metadata
        if deleted is not None:
          self.deleted = deleted

    @property
    def version(self):
        """
        Gets the version of this StackVersionConfig.
        Stack version

        :return: The version of this StackVersionConfig.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this StackVersionConfig.
        Stack version

        :param version: The version of this StackVersionConfig.
        :type: str
        """

        self._version = version

    @property
    def template(self):
        """
        Gets the template of this StackVersionConfig.

        :return: The template of this StackVersionConfig.
        :rtype: StackVersionTemplateInfo
        """
        return self._template

    @template.setter
    def template(self, template):
        """
        Sets the template of this StackVersionConfig.

        :param template: The template of this StackVersionConfig.
        :type: StackVersionTemplateInfo
        """

        self._template = template

    @property
    def elasticsearch(self):
        """
        Gets the elasticsearch of this StackVersionConfig.

        :return: The elasticsearch of this StackVersionConfig.
        :rtype: StackVersionElasticsearchConfig
        """
        return self._elasticsearch

    @elasticsearch.setter
    def elasticsearch(self, elasticsearch):
        """
        Sets the elasticsearch of this StackVersionConfig.

        :param elasticsearch: The elasticsearch of this StackVersionConfig.
        :type: StackVersionElasticsearchConfig
        """

        self._elasticsearch = elasticsearch

    @property
    def kibana(self):
        """
        Gets the kibana of this StackVersionConfig.

        :return: The kibana of this StackVersionConfig.
        :rtype: StackVersionKibanaConfig
        """
        return self._kibana

    @kibana.setter
    def kibana(self, kibana):
        """
        Sets the kibana of this StackVersionConfig.

        :param kibana: The kibana of this StackVersionConfig.
        :type: StackVersionKibanaConfig
        """

        self._kibana = kibana

    @property
    def metadata(self):
        """
        Gets the metadata of this StackVersionConfig.

        :return: The metadata of this StackVersionConfig.
        :rtype: StackVersionMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """
        Sets the metadata of this StackVersionConfig.

        :param metadata: The metadata of this StackVersionConfig.
        :type: StackVersionMetadata
        """

        self._metadata = metadata

    @property
    def deleted(self):
        """
        Gets the deleted of this StackVersionConfig.
        Identifies that the Elastic Stack version is marked for deletion

        :return: The deleted of this StackVersionConfig.
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """
        Sets the deleted of this StackVersionConfig.
        Identifies that the Elastic Stack version is marked for deletion

        :param deleted: The deleted of this StackVersionConfig.
        :type: bool
        """

        self._deleted = deleted

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, StackVersionConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
