# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class StackVersionKibanaConfig(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'docker_image': 'str',
        'blacklist': 'list[str]'
    }

    attribute_map = {
        'version': 'version',
        'docker_image': 'docker_image',
        'blacklist': 'blacklist'
    }

    def __init__(self, version=None, docker_image=None, blacklist=None):
        """
        StackVersionKibanaConfig - a model defined in Swagger
        """

        self._version = None
        self._docker_image = None
        self._blacklist = None

        if version is not None:
          self.version = version
        self.docker_image = docker_image
        self.blacklist = blacklist

    @property
    def version(self):
        """
        Gets the version of this StackVersionKibanaConfig.
        Version of Kibana

        :return: The version of this StackVersionKibanaConfig.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this StackVersionKibanaConfig.
        Version of Kibana

        :param version: The version of this StackVersionKibanaConfig.
        :type: str
        """

        self._version = version

    @property
    def docker_image(self):
        """
        Gets the docker_image of this StackVersionKibanaConfig.
        Docker image for the kibana

        :return: The docker_image of this StackVersionKibanaConfig.
        :rtype: str
        """
        return self._docker_image

    @docker_image.setter
    def docker_image(self, docker_image):
        """
        Sets the docker_image of this StackVersionKibanaConfig.
        Docker image for the kibana

        :param docker_image: The docker_image of this StackVersionKibanaConfig.
        :type: str
        """
        if docker_image is None:
            raise ValueError("Invalid value for `docker_image`, must not be `None`")

        self._docker_image = docker_image

    @property
    def blacklist(self):
        """
        Gets the blacklist of this StackVersionKibanaConfig.
        List of configuration options that cannot be overridden by user settings

        :return: The blacklist of this StackVersionKibanaConfig.
        :rtype: list[str]
        """
        return self._blacklist

    @blacklist.setter
    def blacklist(self, blacklist):
        """
        Sets the blacklist of this StackVersionKibanaConfig.
        List of configuration options that cannot be overridden by user settings

        :param blacklist: The blacklist of this StackVersionKibanaConfig.
        :type: list[str]
        """
        if blacklist is None:
            raise ValueError("Invalid value for `blacklist`, must not be `None`")

        self._blacklist = blacklist

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, StackVersionKibanaConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
