# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TlsPublicCertChain(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_supplied': 'bool',
        'chain': 'list[str]'
    }

    attribute_map = {
        'user_supplied': 'user_supplied',
        'chain': 'chain'
    }

    def __init__(self, user_supplied=None, chain=None):
        """
        TlsPublicCertChain - a model defined in Swagger
        """

        self._user_supplied = None
        self._chain = None

        self.user_supplied = user_supplied
        self.chain = chain

    @property
    def user_supplied(self):
        """
        Gets the user_supplied of this TlsPublicCertChain.
        Was this certificate chain user supplied or automatically generated?

        :return: The user_supplied of this TlsPublicCertChain.
        :rtype: bool
        """
        return self._user_supplied

    @user_supplied.setter
    def user_supplied(self, user_supplied):
        """
        Sets the user_supplied of this TlsPublicCertChain.
        Was this certificate chain user supplied or automatically generated?

        :param user_supplied: The user_supplied of this TlsPublicCertChain.
        :type: bool
        """
        if user_supplied is None:
            raise ValueError("Invalid value for `user_supplied`, must not be `None`")

        self._user_supplied = user_supplied

    @property
    def chain(self):
        """
        Gets the chain of this TlsPublicCertChain.
        The list of PEM encoded X509 certificates that make up the certificate chain

        :return: The chain of this TlsPublicCertChain.
        :rtype: list[str]
        """
        return self._chain

    @chain.setter
    def chain(self, chain):
        """
        Sets the chain of this TlsPublicCertChain.
        The list of PEM encoded X509 certificates that make up the certificate chain

        :param chain: The chain of this TlsPublicCertChain.
        :type: list[str]
        """
        if chain is None:
            raise ValueError("Invalid value for `chain`, must not be `None`")

        self._chain = chain

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TlsPublicCertChain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
